version: '3.8'

services:
  backend:
    container_name: cilist-be
    image: cix-tes-be
    ports:
      - "5000:5000"

  frontend:
    container_name: cilist-fe
    image: cix-tes-fe
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://cilistx.mwbowo.my.id:5000
