FROM node:lts-gallium

WORKDIR /app

COPY . /app

RUN apt update && apt install nano -y

DELETE package.json
DELETE package-lock.json

RUN npm init

RUN npm install socket.io --save 

RUN npm install

EXPOSE 5000

CMD [ "npm", "start" ]
