FROM node:lts-gallium

WORKDIR /app

COPY . /app

RUN apt update && apt install nano -y

RUN rm -rf package.json
RUN rm -rf package-lock.json

RUN npm init

RUN npm install socket.io --save 

RUN npm install

EXPOSE 5000

CMD [ "npm", "start" ]
