apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-be
  labels:
    app: app-be
spec:
  selector:
    matchLabels:
      app: app-be
  template:
    metadata:
      labels:
        app: app-be
    spec:
      containers:
      - name: app-be
        image: mwbowo/cix-be:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: BASE_URL_PORT
            valueFrom:
              configMapKeyRef:
                name: cm-be
                key: BASE_URL_PORT